### ISSUE TITLE
[Mac] Localhost configs

### ISSUE THREAD

**Issue by ysl2** [ysl2/.dotfiles#66]

**Comment by ysl2** [comment]
```bash
# ~/.bashrc.localhost.pre

MYCONDA=~/.vocal/mambaforge
MYNOMIRRORFLAG=1
```

**Comment by ysl2** [comment]
```
# ~/.config/kitty/kitty.localhost.conf

background_opacity 0.7
```

**Comment by ysl2** [comment]
```
# ~/.bashrc.localhost.post

HOMEBREW_NO_AUTO_UPDATE=1

# alias nvim='nvim -u ~/.vimrc'

alias weterm='ssh -o HostKeyAlgorithms=+ssh-rsa -o PubkeyAcceptedKeyTypes=+ssh-rsa ${WECOM_ID}@${JUMPSERVER} -p ${JUMPSERVER_POST_ID}'

PP() {
    http_proxy=127.0.0.1:12639 https_proxy=127.0.0.1:${INNER_POST_ID} "$@"
}
```

**Comment by ysl2** [comment]
```
# ~/.ssh/config.localhost

Host *.devcloud.woa.com
Include  ~/.ssh/devcloud_config
```

**Comment by ysl2** [comment]
Mac ssh local config, need to add company's ssh information. Refer to the original ~/.ssh/config file.

**Comment by ysl2** [comment]
```toml
# ~/.config/alacritty/alacritty.localhost.toml

[font]
size = 12

[window]
startup_mode = 'Maximized'
opacity = 1
option_as_alt = "Both"
```
