### ISSUE TITLE
[Windows] Localhost configs

### ISSUE THREAD

**Issue by ysl2** [ysl2/.dotfiles#80]

**Comment by ysl2** [comment]
`~/.config/alacritty/alacritty.localhost.toml`

```toml
[window]
opacity = 0.7
startup_mode = 'Maximized'

[font]
size = 13

[terminal]
shell = { program = 'pwsh', args = ['-NoLogo -WorkingDirectory ~'] }
```
